### ISSUE TITLE
Import only 1 highlighting language not working

### ISSUE THREAD

**Issue by x1c0** [MurhafSousli/ngx-highlightjs#114] opened 2020-03-09 07:48 UTC
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] question
```

### OS and Version?
macOS Catalina

### Versions
Angular CLI: 9.0.4
Node: 13.2.0
OS: darwin x64

Angular: 9.0.4
... animations, cli, common, compiler, compiler-cli, core, forms
... language-service, platform-browser, platform-browser-dynamic
... router
Ivy Workspace: Yes

Package                            Version
------------------------------------------------------------
@angular-devkit/architect          0.900.4
@angular-devkit/build-angular      0.900.4
@angular-devkit/build-optimizer    0.900.4
@angular-devkit/build-webpack      0.900.4
@angular-devkit/core               9.0.4
@angular-devkit/schematics         9.0.4
@angular/cdk                       9.1.0
@angular/material                  9.1.0
@angular/material-moment-adapter   9.1.0
@ngtools/webpack                   9.0.4
@schematics/angular                9.0.4
@schematics/update                 0.900.4
rxjs                               6.5.4
typescript                         3.7.5
webpack                            4.41.2

### Repro steps
In a lazy loaded module I imported `HighlightModule` and there I defined the provider for `HIGHLIGHT_OPTIONS` like so?:

```
  providers: [
    {
      provide: HIGHLIGHT_OPTIONS,
      useValue: {
        languages: getHighlightLanguages(),
      },
    },
  ],
```
and the function also on that file:

```
function getHighlightLanguages() {
  return {
    json: () => import('highlight.js/lib/languages/json'),
  };
}
```
then when I run `ng build --prod --stats-json` and then `webpack-bundle-analyzer dist/stats.json`
I got this:

![image](https://user-images.githubusercontent.com/2421483/76192517-479a0200-61e2-11ea-8580-9ad1e7916a3b.png)

### Desired functionality
Only core lib + json language is imported into the prod bundle and not all the languages

Thank you in advance for any help!

**Comment by Thilo84** [comment] 2020-03-10 13:38
I have the same issue with Angular 8.

**Comment by MurhafSousli** [comment] 2020-03-13 15:58
I just tried to build the demo app and it appears that it is loading only the 3 languages that are being imported.

Please check the demo app

![Screenshot 2020-03-13 at 16 56 53](https://user-images.githubusercontent.com/8130692/76637773-a9909980-654b-11ea-94b8-b20f7788cb04.png)

**Comment by x1c0** [comment] 2020-03-13 16:04
Sure, Can you please where is the source code for demo app?

**Comment by MurhafSousli** [comment] 2020-03-13 18:07
@x1c0 Here https://github.com/MurhafSousli/ngx-highlightjs/tree/master/src

**Comment by x1c0** [comment] 2020-03-18 16:00
Hi @MurhafSousli I could only try out this today, unfortunately I can't start demo app. Before I started I did:

- `npm install`
- `npm run build-lib`
- `npm run link-lib`
- `npm start`

and then I get this errors:

![image](https://user-images.githubusercontent.com/2421483/76980738-dec92d00-6939-11ea-8977-7ffad82133d6.png)

What am I missing?

**Comment by sergey-morenets** [comment] 2020-03-19 07:14
Hi

The same issue reproduces for me. I selected only 6 six languages in the provider config. But it seems that generated bundle (about 800 kb) contains all the languages includes in Highlight.js

**Comment by sergey-morenets** [comment] 2020-03-19 07:24
Here is my configuration:

```
@NgModule({
  imports: [
    CommonModule,
    HighlightModule
  ],
  providers: [{
    provide: HIGHLIGHT_OPTIONS,
    useValue: {
      languages: hljsLanguages()
    }
  }]
})
export class MyModule {
}

export function hljsLanguages() {
  return {
    typescript: () => import('highlight.js/lib/languages/typescript'),
    css: () => import('highlight.js/lib/languages/css'),
    xml: () => import('highlight.js/lib/languages/xml'),
  };
}
```

**Comment by MurhafSousli** [comment] 2020-03-19 15:48
@x1c0 When you are developing the demo, you should use the local imports instead of the published package name. You should not use npm link in this case.

**Comment by x1c0** [comment] 2020-03-19 20:26
@MurhafSousli can you please help me to run your project? this are the detailed steps I just did:
1. `git clone https://github.com/MurhafSousli/ngx-highlightjs.git`
1.  ` cd ngx-highlightjs    `
1. `npm i`
1. ` ng build ngx-highlightjs   ` -> this is needed right? to build the library
1. `ng serve`
1.  I got this error:
  ```
  ERROR in projects/ngx-highlightjs/plus/src/highlight-plus.module.ts:3:33 - error TS2307: Cannot 
  find module 'ngx-highlightjs'.

 import { HighlightModule } from 'ngx-highlightjs';
                                  ~~~~~~~~~~~~~~~~~
```
7. fixed the error by uncommenting this line:
```
// import { HighlightModule } from 'ngx-highlightjs';
// Uncomment the following line for development
import { HighlightModule } from '../../src/public-api';
```
8. run `ng serve` and got the same errors:
```
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm5/ngx-scrollbar.js 1187:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm5/ngx-scrollbar.js 1190:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm5/ngx-scrollbar.js 1202:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
ERROR in ./node_modules/ngx-scrollbar/__ivy_ngcc__/fesm5/ngx-scrollbar.js 1205:55-72
"export 'RtlScrollAxisType' was not found in '@angular/cdk/platform'
```

**Comment by MurhafSousli** [comment] 2020-03-19 22:54
@x1c0 The error you are getting is  related to @angular/cdk, please verify that you installed `"@angular/cdk": "^9.1.2"` it work properly on my end!

**Comment by x1c0** [comment] 2020-03-20 08:32
@MurhafSousli sorry it doesn't work.. I have not change any dependencies, if you would clone you project again to new folder and run the same commands as I did you will face the same error.. can you please try? Or else is also hard for me to help out :( 

I even tried to use `npm ci` that will only install the dependencies from your `package-lock.json` file to make sure is not a newer version issue.. I have no more ideas on how to go forward

**Comment by istibekesi** [comment] 2020-03-26 23:31
@MurhafSousli @x1c0 
In my dist folder I can see 3 bundles related to this. Most probably, the 2 small ones are `highlight.js` including only the configured languages and the `highlightjs-line-numbers.js`. 
The 3rd big bundle (parsed size is approx 860kB) includes all the languages though. 
It seems it is not loaded indeed, but it it definitely part of the build.

@MurhafSousli - can you check if you can find such a big bundle in your dist folder? 

Two small bundles:
![image](https://user-images.githubusercontent.com/5990010/77705950-572a9080-6fc1-11ea-93a3-7e5c9a1badbc.png)

Third big one:
![image](https://user-images.githubusercontent.com/5990010/77706300-4b8b9980-6fc2-11ea-8d5c-836e8f7fd71d.png)

**Comment by MurhafSousli** [comment] 2020-03-28 14:14
@istibekesi I don't know what project setup you have. try to use the same settings used in the demo app

As you see here https://ngx-highlight.netlify.com/ the bundle size is small. it is only loading the languages I imported.

<img width="1035" alt="Screenshot 2020-03-28 at 15 08 49" src="https://user-images.githubusercontent.com/8130692/77824873-096b7080-7106-11ea-9b57-f0b959795b38.png">

I don't know what you guys are doing wrong. but if you figure out, please write it down so everyone can fix it.

**Comment by MurhafSousli** [comment] 2020-03-28 14:19
Oh and please note this

https://github.com/MurhafSousli/ngx-highlightjs/blob/76287be10e3a11f4d3c624525f884c3422ebf09d/projects/ngx-highlightjs/src/lib/highlight.loader.ts#L51-L53

I suggest that you make sure that `HIGHLIGHT_OPTIONS` is imported in the root module. not in a sub module.

```
export function hljsLanguages() {
  return {
    typescript: () => import('highlight.js/lib/languages/typescript'),
    css: () => import('highlight.js/lib/languages/css'),
    xml: () => import('highlight.js/lib/languages/xml'),
  };
}

@NgModule({
  providers: [{
    provide: HIGHLIGHT_OPTIONS,
    useValue: {
      languages: hljsLanguages()
    }
  }]
})
export class AppModule {
}

```

**Comment by istibekesi** [comment] 2020-03-28 14:37
@MurhafSousli If you build the demo, don't you have an approx 860kB bundle in your `dist` folder?

**Comment by MurhafSousli** [comment] 2020-03-28 14:40
@istibekesi Yes, I do, but it is not loaded!

**Comment by istibekesi** [comment] 2020-03-28 14:42
@MurhafSousli The `webpack-bundle-analyzer` does not know that, most probably this leads to the confusion.

**Comment by MurhafSousli** [comment] 2020-03-28 14:45
Ok, let me explain something. when you use the `import()` function. the webpack-bundle-analyzer will include it in the bundle directory in its own file.

But that does not mean it will be loaded in your app at runtime.. it is just there available waiting for you to call it.

So inside the library, I use `import('the whole library')` just in case you did not provide any language so it loads it.

But if you did provide a language, that file will never be loaded in your app at run time.

This is the same when you lazy loaded modules (routes). they are included in the bundle but not loaded unless they need to

**Comment by MurhafSousli** [comment] 2020-03-28 14:47
I think the issue is clear now. I will close it but feel free to continue the discussion

**Comment by nischi** [comment] 2020-03-30 10:48
I have the same issue. But is that necessary to bundle the whole library if we only use a few languages? It tooks also some time to compile the 800kb if i do not use it. i do not had this issue on other libraries.  Somehow it need to be possible?

**Comment by x1c0** [comment] 2020-03-30 12:03
@MurhafSousli that's the problem, if you import the whole library then this causes all applications that use your library to compile the whole thing. So even though is not loaded on the client side it is  unnecessary.

My suggestion is, instead of you use `import('the whole library')` you could first check if the consumer app is requiring some language (maybe checking `HIGHLIGHT_OPTIONS `), if not, then you could throw some exception.

If we think about this, rather any application would need to feature highlight all the languages right? I would say that by default this library should only load the languages specified by the consumer. It's only my opinion, you're the library creator, so you should decide if makes sense :)

**Comment by MurhafSousli** [comment] 2020-03-30 13:28
@x1c0 I am open for changes

**Comment by MurhafSousli** [comment] 2020-03-30 13:35
Ok let's track this in #122

**Closed by MurhafSousli** 2020-03-30 13:35 UTC

**Comment by istibekesi** [comment] 2020-03-30 13:43
@x1c0 @MurhafSousli 
Another solution could be to load only 2-3 popular, predefined languages by default. 
And this could be extend by further configuration.
(So it won't throw exception... just an idea)
